package com.cafeteria.service.impl;
import com.cafeteria.dto.request.*; import com.cafeteria.dto.response.*; import com.cafeteria.entity.*; import com.cafeteria.entity.enums.*; import com.cafeteria.exception.*; import com.cafeteria.repository.*; import com.cafeteria.service.OrderService; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.LocalDate; import java.util.*;
@Service public class OrderServiceImpl implements OrderService{
 private final OrderRepository orderRepo; private final OrderItemRepository itemRepo; private final MenuItemRepository menuRepo; private final TokenCounterRepository tokenRepo;
 public OrderServiceImpl(OrderRepository o,OrderItemRepository i,MenuItemRepository m,TokenCounterRepository t){orderRepo=o;itemRepo=i;menuRepo=m;tokenRepo=t;}
 @Transactional public OrderResponse placeOrder(PlaceOrderRequest r){if(r==null||r.items()==null||r.items().isEmpty())throw new InvalidOperationException("Order must contain at least one item.");Map<Long,Integer> q=new TreeMap<>();for(OrderLineRequest l:r.items()){if(l==null||l.itemId()==null)throw new InvalidOperationException("Item id is required for every order line.");if(l.quantity()==null||l.quantity()<=0)throw new InvalidQuantityException("Quantity must be greater than zero for item "+l.itemId());q.merge(l.itemId(),l.quantity(),Integer::sum);}
 List<OrderItem> lines=new ArrayList<>();BigDecimal total=BigDecimal.ZERO;for(var e:q.entrySet()){MenuItem m=menuRepo.findByIdForUpdate(e.getKey()).orElseThrow(()->new ItemNotFoundException("Menu item not found: id="+e.getKey()));if(!Boolean.TRUE.equals(m.getIsAvailable()))throw new ItemUnavailableException("Item is not available: "+m.getName());Integer stock=m.getStockQuantity();if(stock!=null&&stock<e.getValue())throw new InsufficientStockException("Insufficient stock for item: "+m.getName());if(stock!=null)m.setStockQuantity(stock-e.getValue());BigDecimal unit=m.getPrice();total=total.add(unit.multiply(BigDecimal.valueOf(e.getValue())));OrderItem oi=new OrderItem();oi.setMenuItem(m);oi.setItemNameSnapshot(m.getName());oi.setQuantity(e.getValue());oi.setUnitPrice(unit);lines.add(oi);}
 LocalDate today=LocalDate.now();tokenRepo.upsertAndIncrement(today);TokenCounter tc=tokenRepo.findByOrderDateForUpdate(today).orElseThrow(()->new InvalidOperationException("Failed to generate token."));Order o=new Order();o.setTokenNumber(tc.getLastToken());o.setOrderDate(today);o.setOrderStatus(OrderStatus.PENDING);o.setPaymentStatus(PaymentStatus.UNPAID);o.setPaymentMethod(r.paymentMethod());o.setTotalAmount(total);o.setNotes(r.notes());o=orderRepo.save(o);for(OrderItem oi:lines)oi.setOrder(o);itemRepo.saveAll(lines);return response(o,lines);}
 @Transactional(readOnly=true) public OrderResponse getOrderById(Long id){Order o=orderRepo.findById(id).orElseThrow(()->new OrderNotFoundException("Order not found: id="+id));return response(o,itemRepo.findByOrder_OrderId(id));}
 @Transactional(readOnly=true) public List<OrderResponse> getOrdersByDate(LocalDate d){if(d==null)d=LocalDate.now();return orderRepo.findByOrderDate(d).stream().map(o->response(o,itemRepo.findByOrder_OrderId(o.getOrderId()))).toList();}
 @Transactional public OrderResponse updateOrderStatus(Long id,OrderStatus s){if(s==null)throw new InvalidOperationException("Order status is required.");Order o=orderRepo.findById(id).orElseThrow(()->new OrderNotFoundException("Order not found: id="+id));o.setOrderStatus(s);return response(o,itemRepo.findByOrder_OrderId(id));}
 @Transactional public OrderResponse updatePaymentStatus(Long id,PaymentStatus s,PaymentMethod m){if(s==null)throw new InvalidOperationException("Payment status is required.");Order o=orderRepo.findById(id).orElseThrow(()->new OrderNotFoundException("Order not found: id="+id));o.setPaymentStatus(s);if(m!=null)o.setPaymentMethod(m);return response(o,itemRepo.findByOrder_OrderId(id));}
 private OrderResponse response(Order o,List<OrderItem> list){List<OrderItemResponse> r=list.stream().map(x->{BigDecimal sub=x.getUnitPrice().multiply(BigDecimal.valueOf(x.getQuantity()));return new OrderItemResponse(x.getOrderItemId(),x.getMenuItem()!=null?x.getMenuItem().getItemId():null,x.getItemNameSnapshot(),x.getQuantity(),x.getUnitPrice(),sub);}).toList();return new OrderResponse(o.getOrderId(),o.getTokenNumber(),o.getOrderDate(),o.getOrderStatus(),o.getPaymentStatus(),o.getPaymentMethod(),o.getTotalAmount(),o.getNotes(),r);}
}
